name: flnexpense
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  sqflite: ^2.3.3+1
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  fl_chart: ^0.69.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.4
  built_value: ^8.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true
  fonts:
    - family: SFText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        
